[build]
  publish = ".next"
  command = "pnpm run build"
[[headers]]
  for = "/*"
    [headers.values]
    X-Robots-Tag = "all"
[[redirects]]
  from = "/*"
  to = "https://www.steameracademy.me/:splat"
  status = 301
  force = true
  conditions = { Host = "steamer-academyme.netlify.app" }
[[plugins]]
  package = "@netlify/plugin-lighthouse"
[dev]
  framework = "#custom"
  command = "pnpm run dev"
  targetPort = 3000
